"""create db

Revision ID: d35e7aac2dd9
Revises: 
Create Date: 2025-12-18 17:00:22.288001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import letta
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'd35e7aac2dd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('privileged_tools', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('message_ids', sa.JSON(), nullable=True),
    sa.Column('response_format', letta.orm.custom_columns.ResponseFormatColumn(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('llm_config', letta.orm.custom_columns.LLMConfigColumn(), nullable=True),
    sa.Column('embedding_config', letta.orm.custom_columns.EmbeddingConfigColumn(), nullable=True),
    sa.Column('compaction_settings', letta.orm.custom_columns.CompactionSettingsColumn(), nullable=True),
    sa.Column('tool_rules', letta.orm.custom_columns.ToolRulesColumn(), nullable=True),
    sa.Column('message_buffer_autoclear', sa.Boolean(), nullable=False),
    sa.Column('enable_sleeptime', sa.Boolean(), nullable=True),
    sa.Column('last_run_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_duration_ms', sa.Integer(), nullable=True),
    sa.Column('last_stop_reason', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('max_files_open', sa.Integer(), nullable=True),
    sa.Column('per_file_view_window_char_limit', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('_vector_db_namespace', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('base_template_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_created_at', 'agents', ['created_at', 'id'], unique=False)
    op.create_index('ix_agents_organization_id_deployment_id', 'agents', ['organization_id', 'deployment_id'], unique=False)
    op.create_index('ix_agents_project_id', 'agents', ['project_id'], unique=False)
    op.create_table('archives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('vector_db_provider', sa.Enum('NATIVE', 'TPUF', 'PINECONE', name='vectordbprovider'), nullable=False),
    sa.Column('embedding_config', letta.orm.custom_columns.EmbeddingConfigColumn(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('_vector_db_namespace', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_archives_created_at', 'archives', ['created_at', 'id'], unique=False)
    op.create_index('ix_archives_organization_id', 'archives', ['organization_id'], unique=False)
    op.create_table('block',
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('preserve_on_migration', sa.Boolean(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('current_history_entry_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('base_template_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_history_entry_id'], ['block_history.id'], name='fk_block_current_history_entry', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'label', name='unique_block_id_label')
    )
    op.create_index('created_at_label_idx', 'block', ['created_at', 'label'], unique=False)
    op.create_index(op.f('ix_block_current_history_entry_id'), 'block', ['current_history_entry_id'], unique=False)
    op.create_index('ix_block_hidden', 'block', ['hidden'], unique=False)
    op.create_index('ix_block_is_template', 'block', ['is_template'], unique=False)
    op.create_index('ix_block_org_project_template', 'block', ['organization_id', 'project_id', 'is_template'], unique=False)
    op.create_index('ix_block_organization_id_deployment_id', 'block', ['organization_id', 'deployment_id'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identifier_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identity_type', sa.String(), nullable=False),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_key', 'project_id', 'organization_id', name='unique_identifier_key_project_id_organization_id', postgresql_nulls_not_distinct=True)
    )
    op.create_table('mcp_server',
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('server_type', sa.String(), nullable=False),
    sa.Column('server_url', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_enc', sa.Text(), nullable=True),
    sa.Column('custom_headers', sa.JSON(), nullable=True),
    sa.Column('custom_headers_enc', sa.Text(), nullable=True),
    sa.Column('stdio_config', letta.orm.custom_columns.MCPStdioServerConfigColumn(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_name', 'organization_id', name='uix_name_organization_mcp_server')
    )
    op.create_table('mcp_tools',
    sa.Column('mcp_server_id', sa.String(), nullable=False),
    sa.Column('tool_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_step_id', 'provider_traces', ['step_id'], unique=False)
    op.create_table('providers',
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=True),
    sa.Column('provider_category', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('access_key_enc', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='unique_name_organization_id')
    )
    op.create_table('sandbox_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('E2B', 'MODAL', 'LOCAL', name='sandboxtype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'organization_id', name='uix_type_organization')
    )
    op.create_table('sources',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('embedding_config', letta.orm.custom_columns.EmbeddingConfigColumn(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('vector_db_provider', sa.Enum('NATIVE', 'TPUF', 'PINECONE', name='vectordbprovider'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='uq_source_name_organization')
    )
    op.create_index('source_created_at_id_idx', 'sources', ['created_at', 'id'], unique=False)
    op.create_table('tools',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tool_type', sa.String(), nullable=False),
    sa.Column('return_char_limit', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=True),
    sa.Column('json_schema', sa.JSON(), nullable=True),
    sa.Column('args_json_schema', sa.JSON(), nullable=True),
    sa.Column('pip_requirements', sa.JSON(), nullable=True),
    sa.Column('npm_requirements', sa.JSON(), nullable=True),
    sa.Column('default_requires_approval', sa.Boolean(), nullable=True),
    sa.Column('enable_parallel_execution', sa.Boolean(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='uix_name_organization'),
    sa.UniqueConstraint('organization_id', 'project_id', 'name', name='uix_organization_project_name', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_tools_created_at_name', 'tools', ['created_at', 'name'], unique=False)
    op.create_index('ix_tools_organization_id', 'tools', ['organization_id'], unique=False)
    op.create_index('ix_tools_organization_id_name', 'tools', ['organization_id', 'name'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_environment_variables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'agent_id', name='uix_key_agent')
    )
    op.create_index('idx_agent_environment_variables_agent_id', 'agent_environment_variables', ['agent_id'], unique=False)
    op.create_table('agents_tags',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tag'),
    sa.UniqueConstraint('agent_id', 'tag', name='unique_agent_tag')
    )
    op.create_index('ix_agents_tags_agent_id_tag', 'agents_tags', ['agent_id', 'tag'], unique=False)
    op.create_index('ix_agents_tags_tag_agent_id', 'agents_tags', ['tag', 'agent_id'], unique=False)
    op.create_table('archival_passages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('embedding_config', letta.orm.custom_columns.EmbeddingConfigColumn(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('embedding', Vector(4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('archive_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('archival_passages_created_at_id_idx', 'archival_passages', ['created_at', 'id'], unique=False)
    op.create_index('ix_archival_passages_archive_id', 'archival_passages', ['archive_id'], unique=False)
    op.create_index('ix_archival_passages_org_archive', 'archival_passages', ['organization_id', 'archive_id'], unique=False)
    op.create_table('archives_agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('archive_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'archive_id'),
    sa.UniqueConstraint('agent_id', name='unique_agent_archive')
    )
    op.create_table('block_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('limit', sa.BigInteger(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_block_history_block_id_sequence', 'block_history', ['block_id', 'sequence_number'], unique=True)
    op.create_table('blocks_agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('block_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['block_id', 'block_label'], ['block.id', 'block.label'], name='fk_block_id_label', onupdate='CASCADE', ondelete='CASCADE', initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('agent_id', 'block_id', 'block_label'),
    sa.UniqueConstraint('agent_id', 'block_id', name='unique_agent_block'),
    sa.UniqueConstraint('agent_id', 'block_label', name='unique_label_per_agent')
    )
    op.create_index('ix_blocks_agents_block_id', 'blocks_agents', ['block_id'], unique=False)
    op.create_index('ix_blocks_agents_block_label_agent_id', 'blocks_agents', ['block_label', 'agent_id'], unique=False)
    op.create_table('files',
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('original_file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_creation_date', sa.String(), nullable=True),
    sa.Column('file_last_modified_date', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('chunks_embedded', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_org_created', 'files', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_files_processing_status', 'files', ['processing_status'], unique=False)
    op.create_index('ix_files_source_created', 'files', ['source_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('manager_type', sa.String(), nullable=False),
    sa.Column('manager_agent_id', sa.String(), nullable=True),
    sa.Column('termination_token', sa.String(), nullable=True),
    sa.Column('max_turns', sa.Integer(), nullable=True),
    sa.Column('sleeptime_agent_frequency', sa.Integer(), nullable=True),
    sa.Column('max_message_buffer_length', sa.Integer(), nullable=True),
    sa.Column('min_message_buffer_length', sa.Integer(), nullable=True),
    sa.Column('turns_counter', sa.Integer(), nullable=True),
    sa.Column('last_processed_message_id', sa.String(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('agent_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('base_template_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manager_agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identities_agents',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', 'agent_id')
    )
    op.create_table('identities_blocks',
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', 'block_id')
    )
    op.create_table('jobs',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('stop_reason', sa.String(), nullable=True),
    sa.Column('background', sa.Boolean(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('request_config', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('callback_sent_at', sa.DateTime(), nullable=True),
    sa.Column('callback_status_code', sa.Integer(), nullable=True),
    sa.Column('callback_error', sa.String(), nullable=True),
    sa.Column('ttft_ns', sa.BigInteger(), nullable=True),
    sa.Column('total_duration_ns', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_user_id', 'jobs', ['user_id'], unique=False)
    op.create_table('mcp_oauth',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('server_id', sa.String(length=255), nullable=True),
    sa.Column('server_url', sa.Text(), nullable=False),
    sa.Column('server_name', sa.Text(), nullable=False),
    sa.Column('authorization_url', sa.Text(), nullable=True),
    sa.Column('authorization_code', sa.Text(), nullable=True),
    sa.Column('authorization_code_enc', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('client_secret', sa.Text(), nullable=True),
    sa.Column('client_secret_enc', sa.Text(), nullable=True),
    sa.Column('redirect_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_server.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('provider_models',
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('model_endpoint_type', sa.String(), nullable=False),
    sa.Column('max_context_window', sa.Integer(), nullable=True),
    sa.Column('supports_token_streaming', sa.Boolean(), nullable=True),
    sa.Column('supports_tool_calling', sa.Boolean(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle', 'organization_id', 'model_type', name='unique_handle_per_org_and_type'),
    sa.UniqueConstraint('name', 'provider_id', 'model_type', name='unique_model_per_provider_and_type')
    )
    op.create_index(op.f('ix_provider_models_handle'), 'provider_models', ['handle'], unique=False)
    op.create_index(op.f('ix_provider_models_model_type'), 'provider_models', ['model_type'], unique=False)
    op.create_index(op.f('ix_provider_models_organization_id'), 'provider_models', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provider_models_provider_id'), 'provider_models', ['provider_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('stop_reason', sa.String(), nullable=True),
    sa.Column('background', sa.Boolean(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('request_config', sa.JSON(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('callback_sent_at', sa.DateTime(), nullable=True),
    sa.Column('callback_status_code', sa.Integer(), nullable=True),
    sa.Column('callback_error', sa.String(), nullable=True),
    sa.Column('ttft_ns', sa.BigInteger(), nullable=True),
    sa.Column('total_duration_ns', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('base_template_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_agent_id', 'runs', ['agent_id'], unique=False)
    op.create_index('ix_runs_created_at', 'runs', ['created_at', 'id'], unique=False)
    op.create_index('ix_runs_organization_id', 'runs', ['organization_id'], unique=False)
    op.create_table('sandbox_environment_variables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('sandbox_config_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sandbox_config_id'], ['sandbox_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'sandbox_config_id', name='uix_key_sandbox_config')
    )
    op.create_table('sources_agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'source_id')
    )
    op.create_index('ix_sources_agents_source_id', 'sources_agents', ['source_id'], unique=False)
    op.create_table('tools_agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tool_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id'),
    sa.UniqueConstraint('agent_id', 'tool_id', name='unique_agent_tool')
    )
    op.create_index('ix_tools_agents_tool_id', 'tools_agents', ['tool_id'], unique=False)
    op.create_table('file_contents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', name='uq_file_contents_file_id')
    )
    op.create_table('files_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('visible_content', sa.Text(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'file_name', name='uq_agent_filename'),
    sa.UniqueConstraint('file_id', 'agent_id', name='uq_file_agent')
    )
    op.create_index('ix_agent_filename', 'files_agents', ['agent_id', 'file_name'], unique=False)
    op.create_index('ix_file_agent', 'files_agents', ['file_id', 'agent_id'], unique=False)
    op.create_table('groups_agents',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'agent_id')
    )
    op.create_table('groups_blocks',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'block_id')
    )
    op.create_table('llm_batch_job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('create_batch_response', letta.orm.custom_columns.CreateBatchResponseColumn(), nullable=False),
    sa.Column('latest_polling_response', letta.orm.custom_columns.PollBatchResponseColumn(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('letta_batch_job_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['letta_batch_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_batch_job_created_at', 'llm_batch_job', ['created_at'], unique=False)
    op.create_index('ix_llm_batch_job_status', 'llm_batch_job', ['status'], unique=False)
    op.create_table('passage_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('passage_id', sa.String(), nullable=False),
    sa.Column('archive_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['passage_id'], ['archival_passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passage_id', 'tag', name='uq_passage_tag')
    )
    op.create_index('ix_passage_tags_org_archive', 'passage_tags', ['organization_id', 'archive_id'], unique=False)
    op.create_index('ix_passage_tags_tag', 'passage_tags', ['tag'], unique=False)
    op.create_table('run_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_start_ns', sa.BigInteger(), nullable=True),
    sa.Column('run_ns', sa.BigInteger(), nullable=True),
    sa.Column('num_steps', sa.Integer(), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('base_template_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_passages',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('embedding_config', letta.orm.custom_columns.EmbeddingConfigColumn(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('embedding', Vector(4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('source_passages_created_at_id_idx', 'source_passages', ['created_at', 'id'], unique=False)
    op.create_index('source_passages_file_id_idx', 'source_passages', ['file_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_category', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('model_endpoint', sa.String(), nullable=True),
    sa.Column('context_window_limit', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens_details', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens_details', sa.JSON(), nullable=True),
    sa.Column('stop_reason', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tid', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', name='stepstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_steps_run_id', 'steps', ['run_id'], unique=False)
    op.create_table('llm_batch_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('llm_batch_id', sa.String(), nullable=False),
    sa.Column('llm_config', letta.orm.custom_columns.LLMConfigColumn(), nullable=False),
    sa.Column('request_status', sa.String(), nullable=False),
    sa.Column('step_status', sa.String(), nullable=False),
    sa.Column('step_state', letta.orm.custom_columns.AgentStepStateColumn(), nullable=False),
    sa.Column('batch_request_result', letta.orm.custom_columns.BatchRequestResultColumn(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_batch_id'], ['llm_batch_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_batch_items_agent_id', 'llm_batch_items', ['agent_id'], unique=False)
    op.create_index('ix_llm_batch_items_llm_batch_id', 'llm_batch_items', ['llm_batch_id'], unique=False)
    op.create_index('ix_llm_batch_items_status', 'llm_batch_items', ['request_status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('content', letta.orm.custom_columns.MessageContentColumn(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tool_calls', letta.orm.custom_columns.ToolCallColumn(), nullable=False),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('step_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('otid', sa.String(), nullable=True),
    sa.Column('tool_returns', letta.orm.custom_columns.ToolReturnColumn(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('batch_item_id', sa.String(), nullable=True),
    sa.Column('is_err', sa.Boolean(), nullable=True),
    sa.Column('approval_request_id', sa.String(), nullable=True),
    sa.Column('approve', sa.Boolean(), nullable=True),
    sa.Column('denial_reason', sa.String(), nullable=True),
    sa.Column('approvals', letta.orm.custom_columns.ApprovalsColumn(), nullable=True),
    sa.Column('sequence_id', sa.BigInteger(), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id')
    )
    op.create_index('idx_messages_step_id', 'messages', ['step_id'], unique=False)
    op.create_index('ix_messages_agent_created_at', 'messages', ['agent_id', 'created_at'], unique=False)
    op.create_index('ix_messages_agent_sequence', 'messages', ['agent_id', 'sequence_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at', 'id'], unique=False)
    op.create_index('ix_messages_org_agent', 'messages', ['organization_id', 'agent_id'], unique=False)
    op.create_index('ix_messages_run_sequence', 'messages', ['run_id', 'sequence_id'], unique=False)
    op.create_table('step_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('step_start_ns', sa.BigInteger(), nullable=True),
    sa.Column('llm_request_start_ns', sa.BigInteger(), nullable=True),
    sa.Column('llm_request_ns', sa.BigInteger(), nullable=True),
    sa.Column('tool_execution_ns', sa.BigInteger(), nullable=True),
    sa.Column('step_ns', sa.BigInteger(), nullable=True),
    sa.Column('base_template_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_step_metrics_run_id', 'step_metrics', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_step_metrics_run_id', table_name='step_metrics')
    op.drop_table('step_metrics')
    op.drop_index('ix_messages_run_sequence', table_name='messages')
    op.drop_index('ix_messages_org_agent', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_agent_sequence', table_name='messages')
    op.drop_index('ix_messages_agent_created_at', table_name='messages')
    op.drop_index('idx_messages_step_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_llm_batch_items_status', table_name='llm_batch_items')
    op.drop_index('ix_llm_batch_items_llm_batch_id', table_name='llm_batch_items')
    op.drop_index('ix_llm_batch_items_agent_id', table_name='llm_batch_items')
    op.drop_table('llm_batch_items')
    op.drop_index('ix_steps_run_id', table_name='steps')
    op.drop_table('steps')
    op.drop_index('source_passages_file_id_idx', table_name='source_passages')
    op.drop_index('source_passages_created_at_id_idx', table_name='source_passages')
    op.drop_table('source_passages')
    op.drop_table('run_metrics')
    op.drop_index('ix_passage_tags_tag', table_name='passage_tags')
    op.drop_index('ix_passage_tags_org_archive', table_name='passage_tags')
    op.drop_table('passage_tags')
    op.drop_index('ix_llm_batch_job_status', table_name='llm_batch_job')
    op.drop_index('ix_llm_batch_job_created_at', table_name='llm_batch_job')
    op.drop_table('llm_batch_job')
    op.drop_table('groups_blocks')
    op.drop_table('groups_agents')
    op.drop_index('ix_file_agent', table_name='files_agents')
    op.drop_index('ix_agent_filename', table_name='files_agents')
    op.drop_table('files_agents')
    op.drop_table('file_contents')
    op.drop_index('ix_tools_agents_tool_id', table_name='tools_agents')
    op.drop_table('tools_agents')
    op.drop_index('ix_sources_agents_source_id', table_name='sources_agents')
    op.drop_table('sources_agents')
    op.drop_table('sandbox_environment_variables')
    op.drop_index('ix_runs_organization_id', table_name='runs')
    op.drop_index('ix_runs_created_at', table_name='runs')
    op.drop_index('ix_runs_agent_id', table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_provider_models_provider_id'), table_name='provider_models')
    op.drop_index(op.f('ix_provider_models_organization_id'), table_name='provider_models')
    op.drop_index(op.f('ix_provider_models_model_type'), table_name='provider_models')
    op.drop_index(op.f('ix_provider_models_handle'), table_name='provider_models')
    op.drop_table('provider_models')
    op.drop_table('mcp_oauth')
    op.drop_index('ix_jobs_user_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('identities_blocks')
    op.drop_table('identities_agents')
    op.drop_table('groups')
    op.drop_index('ix_files_source_created', table_name='files')
    op.drop_index('ix_files_processing_status', table_name='files')
    op.drop_index('ix_files_org_created', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_blocks_agents_block_label_agent_id', table_name='blocks_agents')
    op.drop_index('ix_blocks_agents_block_id', table_name='blocks_agents')
    op.drop_table('blocks_agents')
    op.drop_index('ix_block_history_block_id_sequence', table_name='block_history')
    op.drop_table('block_history')
    op.drop_table('archives_agents')
    op.drop_index('ix_archival_passages_org_archive', table_name='archival_passages')
    op.drop_index('ix_archival_passages_archive_id', table_name='archival_passages')
    op.drop_index('archival_passages_created_at_id_idx', table_name='archival_passages')
    op.drop_table('archival_passages')
    op.drop_index('ix_agents_tags_tag_agent_id', table_name='agents_tags')
    op.drop_index('ix_agents_tags_agent_id_tag', table_name='agents_tags')
    op.drop_table('agents_tags')
    op.drop_index('idx_agent_environment_variables_agent_id', table_name='agent_environment_variables')
    op.drop_table('agent_environment_variables')
    op.drop_table('users')
    op.drop_index('ix_tools_organization_id_name', table_name='tools')
    op.drop_index('ix_tools_organization_id', table_name='tools')
    op.drop_index('ix_tools_created_at_name', table_name='tools')
    op.drop_table('tools')
    op.drop_index('source_created_at_id_idx', table_name='sources')
    op.drop_table('sources')
    op.drop_table('sandbox_configs')
    op.drop_table('providers')
    op.drop_index('ix_step_id', table_name='provider_traces')
    op.drop_table('provider_traces')
    op.drop_table('mcp_tools')
    op.drop_table('mcp_server')
    op.drop_table('identities')
    op.drop_index('ix_block_organization_id_deployment_id', table_name='block')
    op.drop_index('ix_block_org_project_template', table_name='block')
    op.drop_index('ix_block_is_template', table_name='block')
    op.drop_index('ix_block_hidden', table_name='block')
    op.drop_index(op.f('ix_block_current_history_entry_id'), table_name='block')
    op.drop_index('created_at_label_idx', table_name='block')
    op.drop_table('block')
    op.drop_index('ix_archives_organization_id', table_name='archives')
    op.drop_index('ix_archives_created_at', table_name='archives')
    op.drop_table('archives')
    op.drop_index('ix_agents_project_id', table_name='agents')
    op.drop_index('ix_agents_organization_id_deployment_id', table_name='agents')
    op.drop_index('ix_agents_created_at', table_name='agents')
    op.drop_table('agents')
    op.drop_table('prompts')
    op.drop_table('organizations')
    # ### end Alembic commands ###
